package com.tz.redismanager.bean.po;

import java.util.Date;


/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_redis_config
 *
 * @mbg.generated do_not_delete_during_merge Sun May 26 20:25:51 CST 2019
 */
public class RedisConfigPO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.id
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private String id;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.name
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   类型[1=单机,2=集群]
     * @see com.tz.redismanager.constant.ConstInterface.TYPE
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.type
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.address
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private String address;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.password
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private String password;

    /**
     * Database Column Remarks:
     *   序列化代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.ser_code
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private String serCode;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.note
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private String note;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.creater
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private String creater;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.create_time
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.updater
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private String updater;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.update_time
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除[1=是,0=否]
     * @see com.tz.redismanager.constant.ConstInterface.IF_DEL
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_redis_config.if_del
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    private Integer ifDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.id
     *
     * @return the value of t_redis_config.id
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.id
     *
     * @param id the value for t_redis_config.id
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.name
     *
     * @return the value of t_redis_config.name
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.name
     *
     * @param name the value for t_redis_config.name
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.type
     *
     * @return the value of t_redis_config.type
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.type
     *
     * @param type the value for t_redis_config.type
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.address
     *
     * @return the value of t_redis_config.address
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.address
     *
     * @param address the value for t_redis_config.address
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.password
     *
     * @return the value of t_redis_config.password
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.password
     *
     * @param password the value for t_redis_config.password
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.note
     *
     * @return the value of t_redis_config.note
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.note
     *
     * @param note the value for t_redis_config.note
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.creater
     *
     * @return the value of t_redis_config.creater
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.creater
     *
     * @param creater the value for t_redis_config.creater
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.create_time
     *
     * @return the value of t_redis_config.create_time
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.create_time
     *
     * @param createTime the value for t_redis_config.create_time
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.updater
     *
     * @return the value of t_redis_config.updater
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.updater
     *
     * @param updater the value for t_redis_config.updater
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.update_time
     *
     * @return the value of t_redis_config.update_time
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.update_time
     *
     * @param updateTime the value for t_redis_config.update_time
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.if_del
     *
     * @return the value of t_redis_config.if_del
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public Integer getIfDel() {
        return ifDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.if_del
     *
     * @param ifDel the value for t_redis_config.if_del
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setIfDel(Integer ifDel) {
        this.ifDel = ifDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_redis_config.ser_code
     *
     * @return the value of t_redis_config.ser_code
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public String getSerCode() {
        return serCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_redis_config.ser_code
     *
     * @param serCode the value for t_redis_config.ser_code
     *
     * @mbg.generated Sun May 26 20:25:51 CST 2019
     */
    public void setSerCode(String serCode) {
        this.serCode = serCode == null ? null : serCode.trim();
    }

    @Override
    public String toString() {
        return "RedisConfigPO{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", type=" + type +
                ", address='" + address + '\'' +
                ", password='" + password + '\'' +
                ", note='" + note + '\'' +
                ", creater='" + creater + '\'' +
                ", createTime=" + createTime +
                ", updater='" + updater + '\'' +
                ", updateTime=" + updateTime +
                ", ifDel=" + ifDel +
                ", serCode='" + serCode + '\'' +
                '}';
    }
}